### ISSUE TITLE
Verify Downloaded Maven Binary

### ISSUE THREAD

**Issue by vjkoskela** [rimerosolutions/maven-wrapper#11]
If the distribution repository is a complete Maven repository then along with the Maven binary will be various checksum files (e.g. apache-maven-3.3.9-bin.tar.gz.md5). If present (and/or also directed to) one of these checksums should be downloaded and used to verify the correctness of the binary artifact. Although this has not been a major issue it has bitten us twice already. The verification logic could be added as a step in the [Installer](https://github.com/rimerosolutions/maven-wrapper/blob/master/src/main/java/org/apache/maven/wrapper/Installer.java).

See: https://repository.apache.org/content/repositories/releases/org/apache/maven/apache-maven/3.3.9/

**Comment by yveszoundi** [comment]
Hello @vjkoskela,

It's a great idea and indeed the logic could be within the Installer.

I think that the wrapper properties file should be updated for the following:
- Whether or not a checksum should be performed, given the related file is available (HEAD request)
- Checksum file extension (`.md5`, `.sha1`, etc.)
- Checksum method/algorithm, JDK built-in (`MD5`, `SHA-1`, etc.)

From an error handling perspective, appropriate feedback should be displayed:
`Update the wrapper properties....`, also `go and check if the file has been tempered with....`

Optionally, it might be worth trusting all SSL certificates by default. That would take care of `homemade` certificates for custom download locations over HTTPS, expired certificates, etc.

**Comment by vjkoskela** [comment]
Excellent. I've gone ahead and put together a pull request for this. Just a couple of clarifications.

First, by default verification is disabled for backwards compatibility. If explicitly configured to perform verification and the verification file is unavailable from the server the execution will fail. As you suggest, there is a potential enhancement here to allow for non-strict verification. In such a case the verification is only performed if configured to do so _and_ the verification file is present on the server. I can file a follow-up issue to add a less strict verification option if you like.

Second, although I have unfortunately come across such home-grown HTTPS setups it is not too difficult or expensive these days to generate valid certificates and configure the JVM to use them. Additionally, I would prefer not to mix features into this issue or pull request but I can file a follow-up issue to add more permissive HTTPS connectivity if you like.

Here's the PR: #12

**Comment by yveszoundi** [comment]
Merged PR #12

**Comment by yveszoundi** [comment]
I did some refactoring today in order to simplify couple of things, in additional to general cleanup.

- Checksum URIs can be implied from distribution URIs, as it's only about appending the file extension  for supported algorithms (md5 or sha1).
- Using a single checksum algorithm is the most common use case IMHO. checksum.getDefaultExtension()= is good enough at this time.

I requested the push of release 0.0.5 to Maven central today, it will take couple 2-3 days to be GA. Let me know if there are more improvements or flexibility needed for your current use cases.

**Comment by vjkoskela** [comment]
Sounds good to me! Just a quick question. Did this change the plugin configuration or just the structure of the maven/maven-wrapper.properties? Assuming it's the latter, I assume it is no longer backwards compatible (which is fine since this is 0.Y.Z) -- is that correct?

**Comment by yveszoundi** [comment]
I changed a little bit the configuration, minor cleanup is needed to remove the checksum extension (unused). I didn't notice any odd behaviour with old wrapper properties and the new plugin version (file copy). 

The existing properties syntax is still supported. Because the default value of _verifyDownload_ is false in the plugin Mojo, all seems ok. Still, people upgrading to the newer version will have to specify the _checksumAlgorithm_ IF they wish to check the Maven archive integrity(_verifyDownload_ -> true).

I think that it makes sense to just re-generate the plugin and update the configuration as needed when migrating to the latest version. I should probably maintain some kind of changelog file as I don't make use of the Github releases page.
